# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extendedAssetWidget02.ui'
#
# Created: Wed Aug 26 18:02:35 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_versionAssetBlock(object):
    def setupUi(self, versionAssetBlock):
        versionAssetBlock.setObjectName("versionAssetBlock")
        versionAssetBlock.setEnabled(True)
        versionAssetBlock.resize(640, 75)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(versionAssetBlock.sizePolicy().hasHeightForWidth())
        versionAssetBlock.setSizePolicy(sizePolicy)
        versionAssetBlock.setMinimumSize(QtCore.QSize(0, 75))
        versionAssetBlock.setMaximumSize(QtCore.QSize(16777215, 75))
        self.gridLayout_2 = QtGui.QGridLayout(versionAssetBlock)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.versionAssetMainFrame = QtGui.QFrame(versionAssetBlock)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionAssetMainFrame.sizePolicy().hasHeightForWidth())
        self.versionAssetMainFrame.setSizePolicy(sizePolicy)
        self.versionAssetMainFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.versionAssetMainFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.versionAssetMainFrame.setObjectName("versionAssetMainFrame")
        self.gridLayout = QtGui.QGridLayout(self.versionAssetMainFrame)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.status_indicator = QtGui.QToolButton(self.versionAssetMainFrame)
        self.status_indicator.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../opt/OpenTools/Icons/green-on-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.status_indicator.setIcon(icon)
        self.status_indicator.setIconSize(QtCore.QSize(32, 32))
        self.status_indicator.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.status_indicator.setAutoRaise(True)
        self.status_indicator.setArrowType(QtCore.Qt.NoArrow)
        self.status_indicator.setObjectName("status_indicator")
        self.horizontalLayout.addWidget(self.status_indicator)
        self.asset_name = QtGui.QLabel(self.versionAssetMainFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.asset_name.setFont(font)
        self.asset_name.setObjectName("asset_name")
        self.horizontalLayout.addWidget(self.asset_name)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.line_2 = QtGui.QFrame(self.versionAssetMainFrame)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.versionlist = QtGui.QComboBox(self.versionAssetMainFrame)
        self.versionlist.setObjectName("versionlist")
        self.horizontalLayout.addWidget(self.versionlist)
        self.getVersion_but = QtGui.QToolButton(self.versionAssetMainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getVersion_but.sizePolicy().hasHeightForWidth())
        self.getVersion_but.setSizePolicy(sizePolicy)
        self.getVersion_but.setMinimumSize(QtCore.QSize(38, 39))
        self.getVersion_but.setMaximumSize(QtCore.QSize(38, 39))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../opt/OpenTools/Icons/build-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.getVersion_but.setIcon(icon1)
        self.getVersion_but.setIconSize(QtCore.QSize(32, 32))
        self.getVersion_but.setAutoRaise(True)
        self.getVersion_but.setObjectName("getVersion_but")
        self.horizontalLayout.addWidget(self.getVersion_but)
        self.line_3 = QtGui.QFrame(self.versionAssetMainFrame)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.live_label = QtGui.QLabel(self.versionAssetMainFrame)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.live_label.setFont(font)
        self.live_label.setObjectName("live_label")
        self.horizontalLayout.addWidget(self.live_label)
        self.getLive_but = QtGui.QToolButton(self.versionAssetMainFrame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../opt/OpenTools/Icons/agt_action_success-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.getLive_but.setIcon(icon2)
        self.getLive_but.setIconSize(QtCore.QSize(32, 32))
        self.getLive_but.setAutoRaise(True)
        self.getLive_but.setObjectName("getLive_but")
        self.horizontalLayout.addWidget(self.getLive_but)
        self.line = QtGui.QFrame(self.versionAssetMainFrame)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.delete_but = QtGui.QToolButton(self.versionAssetMainFrame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../opt/OpenTools/Icons/cnrdelete-all-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_but.setIcon(icon3)
        self.delete_but.setIconSize(QtCore.QSize(32, 32))
        self.delete_but.setAutoRaise(True)
        self.delete_but.setObjectName("delete_but")
        self.horizontalLayout.addWidget(self.delete_but)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.versionAssetMainFrame, 0, 0, 1, 1)
        self.shotSetupFrame = QtGui.QFrame(versionAssetBlock)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shotSetupFrame.sizePolicy().hasHeightForWidth())
        self.shotSetupFrame.setSizePolicy(sizePolicy)
        self.shotSetupFrame.setMinimumSize(QtCore.QSize(0, 32))
        self.shotSetupFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.shotSetupFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.shotSetupFrame.setObjectName("shotSetupFrame")
        self.gridLayout_3 = QtGui.QGridLayout(self.shotSetupFrame)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.littleled = QtGui.QToolButton(self.shotSetupFrame)
        self.littleled.setMinimumSize(QtCore.QSize(16, 16))
        self.littleled.setMaximumSize(QtCore.QSize(16, 16))
        self.littleled.setIcon(icon)
        self.littleled.setIconSize(QtCore.QSize(16, 16))
        self.littleled.setAutoRaise(True)
        self.littleled.setObjectName("littleled")
        self.horizontalLayout_2.addWidget(self.littleled)
        spacerItem2 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_2 = QtGui.QLabel(self.shotSetupFrame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.setupversionlist = QtGui.QComboBox(self.shotSetupFrame)
        self.setupversionlist.setMinimumSize(QtCore.QSize(0, 24))
        self.setupversionlist.setMaximumSize(QtCore.QSize(16777215, 24))
        self.setupversionlist.setObjectName("setupversionlist")
        self.horizontalLayout_2.addWidget(self.setupversionlist)
        self.getSetupVersion_but = QtGui.QToolButton(self.shotSetupFrame)
        self.getSetupVersion_but.setMinimumSize(QtCore.QSize(24, 24))
        self.getSetupVersion_but.setMaximumSize(QtCore.QSize(24, 24))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../opt/OpenTools/Icons/kdevelop_down-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.getSetupVersion_but.setIcon(icon4)
        self.getSetupVersion_but.setIconSize(QtCore.QSize(16, 16))
        self.getSetupVersion_but.setObjectName("getSetupVersion_but")
        self.horizontalLayout_2.addWidget(self.getSetupVersion_but)
        spacerItem3 = QtGui.QSpacerItem(40, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.shotSetupFrame, 1, 0, 1, 1)

        self.retranslateUi(versionAssetBlock)
        QtCore.QMetaObject.connectSlotsByName(versionAssetBlock)

    def retranslateUi(self, versionAssetBlock):
        versionAssetBlock.setWindowTitle(QtGui.QApplication.translate("versionAssetBlock", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_name.setText(QtGui.QApplication.translate("versionAssetBlock", "Software_test_name (v12)", None, QtGui.QApplication.UnicodeUTF8))
        self.getVersion_but.setText(QtGui.QApplication.translate("versionAssetBlock", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.live_label.setText(QtGui.QApplication.translate("versionAssetBlock", "(v025)", None, QtGui.QApplication.UnicodeUTF8))
        self.getLive_but.setText(QtGui.QApplication.translate("versionAssetBlock", "Live", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_but.setText(QtGui.QApplication.translate("versionAssetBlock", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.littleled.setText(QtGui.QApplication.translate("versionAssetBlock", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("versionAssetBlock", "Scene setup:", None, QtGui.QApplication.UnicodeUTF8))
        self.getSetupVersion_but.setText(QtGui.QApplication.translate("versionAssetBlock", "Set", None, QtGui.QApplication.UnicodeUTF8))

